spring:
 application:
  name: some
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8081/eureka/
 instance:
  leaseRenewalIntervalInSeconds: 1
  leaseExpirationDurationInSeconds: 2

server:
 port: 8082

